### ISSUE TITLE
lsa.convert.data does not convert eTIMSS with PSI cycle from the TIMSS 2019 data

### ISSUE THREAD

**Issue by pehkawn** [cran/RALSA#1]
I've been trying to use `lsa.convert.data` to convert the TIMSS 2019 dataset downloaded from [IEA's repository](https://www.iea.nl/data-tools/repository). Doing so I faced two issues: First, the function does not convert the data if the cycles (Main, m7; Bridge, b7; and eTIMSS with PSI, z7) aren't separated. By separating the datasets in different folders, I managed to convert the main cycle and the bridge cycle, however when trying to convert the eTIMSS with PSI cycle, the function simply exits without converting any of the data. A brief look at the function's code, it seems it lacks a method for handling files where the file name ends with "z7" (lines 672-677).

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by pehkawn** [comment]
Thanks for your reply. I have now sent the bug report through the author's web site.
